/* SECCION 3: DATOS DEL SOLICITANTE */

/* Gentilicios */
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Afgano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Albanés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Alemán/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Andorrano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Angoleño/ña; Angolano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Antigua y Antiguano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Arabia Saudí o saudita',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Argelino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Argentino/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Armenio/nia',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Australiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Austriaco/ca; Austríaco/ca',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Azerbaiyano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Bahameño/ña',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Bangladesí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Barbadense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Bareiní',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Belga',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Beliceño/ña',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Beninés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Bielorruso/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Birmano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Boliviano/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Bosnia y Bosnio/nia; Bosnioherzegovino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Botsuano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Brasileño/a; Brasilero/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Bruneano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Búlgaro/ra',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Burkina Burkinés',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Burundés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Butanés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Cabo Caboverdiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Camboyano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Camerunés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Canadiense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Catarí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Chadiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Chileno/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Chino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Chipriota',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Ciudad del Vaticano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Colombiano/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Comorense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Corea del Norcoreano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Corea del Surcoreano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Costa de Marfileño/ña',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Costa Costarricense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Croata',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Cubano/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Danés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Dominiqués',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Ecuatoriano/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Egipcio/cia',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('El Salvadoreño/ña',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Emiratos Árabes Emiratí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Eritreo/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Eslovaco/ca',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Esloveno/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Español/la',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Estadounidense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Estonio/nia',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Etíope',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Filipino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Finlandés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Fiyiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Francés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Gabonés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Gambiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Georgiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Ghanés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Granadino/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Griego/ga',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Guatemalteco/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Guinea Ecuatoguineano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Guineano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Guinea-Guineano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Guyanés/esa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Haitiano/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Hondureño/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Húngaro/ra',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Indio/dia; Hindú',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Indonesio/sia',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Iraquí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Iraní',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Irlandés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Islandés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Islas Marshalés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Islas Salomonense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Israelí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Italiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Jamaicano/na o Jamaiquino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Japonés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Jordano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Kazajo/ja',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Keniano/na; Keniata',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Kirguís; Kirguiso/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Kiribatiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Kuwaití',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Laosiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Lesotense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Letón/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Libanés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Liberiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Libio/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('liechtensteiniano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Lituano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Luxemburgués/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Malgache',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Malasio/sia',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Malauí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Maldivo/va',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Maliense, Malí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Maltés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Marroquí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Mauriciano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Mauritano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Mexicano/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Micronesio/sia',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Moldavo/va',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Monegasco/ca',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Mongol/la',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Montenegrino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Mozambiqueño/ña',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Namibio/bia',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Nauruano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Nepalés/sa; Nepalí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Nicaragüense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Nigerino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Nigeriano /na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Noruego/ga',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Nueva Neozelandés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Omaní',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Países Neerlandés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Pakistaní',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Palauano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Panameño/ña',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Papúa Nueva Papú',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Paraguayo/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Peruano/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Polaco/ca',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Portugués/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Reino Británico/ca',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Centroafricano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Checo/ca',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Macedonio/nia',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Congoleño/ña',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Congoleño/ña (República Democrática)',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Dominicano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Sudafricano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Ruandés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Rumano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Ruso/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Samoano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Cristobaleño/ña',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Sanmarinense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Sanvicentino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Santalucense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Santotomense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Senegalés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Serbio/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Seychellense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Sierraleonés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Singapurense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Sirio/ria',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Somalí',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Ceilanés/sa; Ceilandés; Esrilanqués/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Suazi',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Sudán del Sursudanés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Sudanés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Sueco/ca',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Suizo/za',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Surinamés/esa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Tailandés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Tanzano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Tayiko/ka',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Timorense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Togolés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Tongano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Trinitense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Tunecino/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Turcomano/na; Turkmeno/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Turco/ca',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Tuvaluano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Ucraniano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Ugandés/sa',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Uruguayo/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Uzbeko/ka',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Vanuatuense',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Venezolano/a',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Vietnamita',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Yemení',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Yibutiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Zambiano/na',1);
insert into t304_c_nacionalidad(ds_nacionalidad, st_vigente) values ('Zimbabuense',1);

/* Nivel de Estudios */
insert into t305_c_nivelestudios(ds_nivelestudios, st_vigente) values ('Experiencia Laboral', 1);
insert into t305_c_nivelestudios(ds_nivelestudios, st_vigente) values ('Nivel Medio Superior', 1);
insert into t305_c_nivelestudios(ds_nivelestudios, st_vigente) values ('Carrera Técnica', 1);
insert into t305_c_nivelestudios(ds_nivelestudios, st_vigente) values ('Licenciatura Trunca', 1);
insert into t305_c_nivelestudios(ds_nivelestudios, st_vigente) values ('Licenciatura Terminada', 1);
insert into t305_c_nivelestudios(ds_nivelestudios, st_vigente) values ('Titulado', 1);
insert into t305_c_nivelestudios(ds_nivelestudios, st_vigente) values ('Posgrado', 1);

/* Tipo de teléfono */
insert into t307_c_tipotelefono(ds_tipotelefono, st_vigente) values ('Particular', 1);
insert into t307_c_tipotelefono(ds_tipotelefono, st_vigente) values ('Celular', 1);
insert into t307_c_tipotelefono(ds_tipotelefono, st_vigente) values ('Oficina', 1);

/* Status de solicitud */
insert into t404_c_statussolicitud(ds_statussolicitud, st_vigente) values ('Pendiente', 1);
insert into t404_c_statussolicitud(ds_statussolicitud, st_vigente) values ('En revisión', 1);
insert into t404_c_statussolicitud(ds_statussolicitud, st_vigente) values ('Aprobada', 1);
insert into t404_c_statussolicitud(ds_statussolicitud, st_vigente) values ('Rechazada', 1);

/* Tipo de documento */
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Copia de la Identificación Oficial', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Comprobante Oficial de Estudios con Reconocimiento Oficial con sello y firma', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Constancia Laboral', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Manifestación Bajo Protesta de Decir Verdad', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Copia de la Cédula del RFC, o Estado de Cuenta de Afore o Estado de Cuenta de Infonavit', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Reporte de Crédito Especial – Personas Físicas', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Documentos Complementos al Buró de Crédito', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Copia de la Identificación Oficial', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Comprobante de Pago del Servicio Solicitado', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Acreditación de los Puntos por Experiencia y Capacitación para la Actualización de la Certificación', 1);
insert into t405_c_tipodoc(ds_tipodoc, st_vigente) values ('Copia Cédula Fiscal emitida por la SHCP (Solicitantes de Facturación)', 1);

/* Tipo de Servicio */
insert into t406_c_tiposervicio(id, ds_tiposervicio, st_vigente) values (1, 'Certificación: Inicial por Exámen', 1);
insert into t406_c_tiposervicio(id, ds_tiposervicio, st_vigente) values (2, 'Certificación: Actualización Certificación', 1);
insert into t406_c_tiposervicio(id, ds_tiposervicio, st_vigente) values (3, 'Autorización: Inicial', 1);
insert into t406_c_tiposervicio(id, ds_tiposervicio, st_vigente) values (4, 'Autorización: Cambio de Figura', 1);
insert into t406_c_tiposervicio(id, ds_tiposervicio, st_vigente) values (5, 'Autorización: Reposición de la Autorización', 1);
insert into t406_c_tiposervicio(id, ds_tiposervicio, st_vigente) values (6, 'Autorización: Actualización Autorización', 1);
insert into t406_c_tiposervicio(id, ds_tiposervicio, st_vigente) values (7, 'Integración del Servicio: Certificación y Autorización', 1);
insert into t406_c_tiposervicio(id, ds_tiposervicio, st_vigente) values (8, 'Integración del Servicio: Actualización de Certificación y Autorización', 1);

/* Forma de Pago */
insert into t407_c_formapago(ds_formapago, st_vigente) values ('CMMV', 1);
insert into t407_c_formapago(ds_formapago, st_vigente) values ('Ficha de Pago', 1);
insert into t407_c_formapago(ds_formapago, st_vigente) values ('Transferencia', 1);
insert into t407_c_formapago(ds_formapago, st_vigente) values ('Carta Promesa de Pago', 1);
insert into t407_c_formapago(ds_formapago, st_vigente) values ('Convenio', 1);
insert into t407_c_formapago(ds_formapago, st_vigente) values ('No Aplica', 1);

/* Figura */
insert into t408_c_figura(ds_figura, st_vigente) values ('Asesor de Estrategias de Inversión (Serie 210) AEI', 1);
insert into t408_c_figura(ds_figura, st_vigente) values ('Promotor de Sociedades de Inversión (Serie 100) PSI', 1);
insert into t408_c_figura(ds_figura, st_vigente) values ('Promotor de Valores (Serie 200) PV', 1);
insert into t408_c_figura(ds_figura, st_vigente) values ('Operador de Bolsa (Serie 220) OB', 1);
insert into t408_c_figura(ds_figura, st_vigente) values ('Operador de Mercado de Dinero (Serie 240) OMD', 1);
insert into t408_c_figura(ds_figura, st_vigente) values ('Administrador de Riesgos para Sociedades de Inversión (Serie 270) ARSI (No requiere Autorización)', 1);
insert into t408_c_figura(ds_figura, st_vigente) values ('Contralor Normativo en Riesgos para Sociedades de Inversión (Serie 280) (No requiere Autorización)', 1);
insert into t408_c_figura(ds_figura, st_vigente) values ('Supervisor de la Mesa de Capitales (Curso-Examen) (Serie 290) (No requiere Autorización)', 1);

/* Tipo de Exámen */
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Primera Vez', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Extraordinario', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de PSI-PV (Serie 100-200)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de PSI-AEI (Serie 100-210)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de PV-AEI (Serie 200-210)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de AEI-OB (Serie 210-220)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de AEI-OMD (Serie 210-240)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de OB-OMD (Serie 220-240)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de OMD-OB (Serie 240-220)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de OB-AEI (Serie 220-210)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Figura Escalonada de OMD-AEI (Serie 240-210)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Examen Modular de AEI (DAF o EFA de EFPA España-Serie 210)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Examen Modular de AEI (DAF o EFA de EFPA España-Serie 210)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Examen Modular de AEI (Series 7 de FINRA-Serie 210)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Examen Modular de OB (Series 7 de FINRA-Serie 220)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Examen Modular de OMD (Series 7 de FINRA-Serie 240)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('Examen Modular de AEI (Niveles I, II y III de CFA-Serie 210)', 1);
insert into t409_c_tipoexamen(ds_tipoexamen, st_vigente) values ('No Aplica', 1);

/* Modalidad de capacitación */
insert into t410_c_modalcapacitacion(ds_modalcapacitacion, st_vigente) values ('E-Learning', 1);
insert into t410_c_modalcapacitacion(ds_modalcapacitacion, st_vigente) values ('Presencial', 1);
insert into t410_c_modalcapacitacion(ds_modalcapacitacion, st_vigente) values ('Mixto', 1);

/* Horarios de examen  */
insert into t411_c_horarioexamen(ds_horarioexamen, st_vigente) values ( '09:00', 1);
insert into t411_c_horarioexamen(ds_horarioexamen, st_vigente) values ( '14:00', 1);

/* Modalidad de actualización de certificación */
insert into t412_c_modalactcert(ds_modalactcert, st_vigente) values ( 'Exámen', 1);
insert into t412_c_modalactcert(ds_modalactcert, st_vigente) values ( 'Puntos', 1);

/* Institutos capacitadores */
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ASTER Education Center Mérida', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Aplicaciones Tecnológicas Var S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Asociación Mexicana de Intermediarios Bursátiles', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Asociación de Bancos de México ABM (Academia ABM)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('B&G Business & Growth S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('B-one', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('BMV, Educación', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('CFA Society of México A.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('CLIEP', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Capacitación Burmed S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Capacitación Financiera, S.C. (KAPFIN)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Centro Peninsular de Capacitación', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Centro de Estudios en Finanzas Institucionales', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Centros Culturales de México A.C. (Universidad Panamericana)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Chagin y Asociados', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Chiu y Hernández Consultores S. de R.L. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Coburfin S. de R.L. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Colegio de Alta de Dirección de Empresas (Puebla)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Collignon Consultores y Capacitadores Bursátiles', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Creando Ejecutivos Certificados S.A. de C.V. ', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Cursos Internos', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Der & Risk S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('EPISE', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Educacorp S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Escuela Bancaria Comercial (EBC)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Fibur, S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Fundación de Investigación para el Desarrollo Profesional, S.C. (FINDES)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('GET Consulting', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Global Derivatives S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Grupo de Especialistas en Capacitación y Consultoría S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ICE Capacitación Especializada, S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('IDEFI Consultores, S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('IMECAF México, S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Aguascalientes', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Chihuahua', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Ciudad de México', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Culiacán', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Estado de México', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Guadalajara', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Hidalgo', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Laguna', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus León', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Monterrey', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Puebla', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Querétaro', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('ITESM Campus Santa Fe', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Instituto Finbur, S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Instituto Tecnológico de Sonora', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Instituto de Capacitación Especializada (ICE)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Instituto de Especialización para Ejecutivos S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Instituto del Mercado de Valores (IMERVAL)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Instituto para Ejecutivos Bursátiles (INBU) (Guadalajara)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('JLL México, Asesoría Financiera y Comercial, S.A.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('JM Capacitación S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Latin Institute of Finance S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Laura Garza y Asociados S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Leading Markets, S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Lobo Global Advisors Lic', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('MR Cursar', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('María Gabriela Siller Pagaza', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('MexDer Mercado Mexicano de Derivados, S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Mikishko Consulting S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Moreno Padilla y Cía., S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('PIM Latam S.A. de C.V. (Proveedor Integral de Precios)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('PROCAP, Servicios de Consultoría Con S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Proveedor de Capacitación Presencial  y Virtual Bursafin S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('QCF Consulting Group S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Resulta Asesoría Patrimonial S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Riskmathics Financial Innovation, S.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Servicios de Consultoría, S.C. (PROCAP)', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Shirebrook Commodities, S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Shirebrook Training S.A. de C.V.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('T.I,C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Universidad Autónoma de Aguascalientes', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Universidad Iberoamericana A.C.', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('Universidad Panamericana Campus Ciudad de México', 1);
insert into t413_c_institutocapacitador(nm_institutocapacitador, st_vigente) values ('No Aplica', 1);
