/*
-- Query: select id_202_municipio,cve_ciudad,nm_ciudad,st_vigente from t204_c_ciudad
-- Date: 2013-10-09 11:14
*/
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1,'01','Aguascalientes',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2,'07','Asientos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (3,'02','Calvillo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (4,'09','Cosío',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (5,'04','Jesús María ',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (6,'05','Pabellón de Arteaga',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (7,'06','Rincón de Romos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (9,'08','Tepezalá',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (11,'03','San Francisco de los Romo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (12,'06','Rodolfo Sánchez T. (Maneadero)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (12,'01','Ensenada',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (13,'02','Mexicali',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (13,'07','San Felipe',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (14,'03','Tecate',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (15,'04','Tijuana',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (16,'05','Playas de Rosarito',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (17,'06','Puerto Adolfo López Mateos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (17,'01','Ciudad Constitución',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (18,'08','Heroica Mulegé',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (18,'10','San Ignacio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (18,'09','Villa Alberto Andrés Alvarado Arámburo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (18,'11','Guerrero Negro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (19,'02','La Paz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (19,'07','Todos Santos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (20,'04','San José del Cabo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (20,'03','Cabo San Lucas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (21,'05','Loreto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (22,'03','Calkini',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (23,'01','San Francisco de Campeche',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (24,'02','Ciudad del Carmen',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (24,'06','Sabancuy',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (25,'08','Champotón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (26,'09','Hecelchakán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (26,'11','Pomuch',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (27,'07','Hopelchén',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (30,'05','Escárcega',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (32,'04','Candelaria',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (34,'01','Ciudad Acuña',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (35,'24','Allende',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (36,'23','Arteaga',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (38,'12','Castaños',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (39,'14','Cuatro Ciénegas de Carranza',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (41,'13','Francisco I. Madero (Chávez)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (42,'02','Frontera',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (49,'03','Matamoros',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (50,'04','Monclova',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (51,'22','Morelos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (52,'20','Ciudad Melchor Múzquiz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (53,'15','Nadadores',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (54,'17','Nava',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (56,'05','Parras de la Fuente',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (57,'06','Piedras Negras',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (59,'16','Ramos Arizpe',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (60,'07','Sabinas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (62,'08','Saltillo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (63,'19','San Buenaventura',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (64,'09','Nueva Rosita',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (65,'10','San Pedro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (67,'11','Torreón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (68,'21','Viesca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (70,'18','Zaragoza',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (71,'05','Ciudad de Armería',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (72,'01','Colima',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (77,'02','Manzanillo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (79,'03','Tecoman',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (80,'04','Ciudad de Villa de Álvarez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (82,'25','Acala',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (89,'09','Arriaga',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (95,'16','Cacahoatán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (97,'18','Cintalapa de Figueroa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (99,'01','Comitán de Domínguez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (107,'15','Chiapa de Corzo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (120,'23','Huixtla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (126,'06','Jiquipilas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (131,'13','Mapastepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (132,'08','Las Margaritas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (137,'24','Motozintla de Mendoza',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (139,'11','Ocosingo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (141,'17','Ocozocoautla de Espinosa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (145,'10','Palenque',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (148,'19','Pichucalco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (149,'21','Pijijiapan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (154,'22','Reforma',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (155,'14','Las Rosas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (158,'02','San Cristóbal de las Casas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (169,'20','Puerto Madero (San Benito)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (169,'03','Tapachula de Córdova y Ordóñez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (176,'12','Tonalá',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (180,'04','Tuxtla Gutiérrez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (185,'05','Venustiano Carranza',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (187,'07','Villaflores',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (200,'11','Juan Aldama',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (204,'14','Bachíniva',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (209,'01','Santa Rosalía de Camargo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (215,'03','Cuauhtémoc',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (215,'10','Colonia Anáhuac',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (217,'02','Chihuahua',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (219,'04','Delicias',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (230,'05','Hidalgo del Parral',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (234,'12','José Mariano Jiménez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (235,'06','Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (238,'09','Madera',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (248,'07','Nuevo Casas Grandes',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (250,'13','Manuel Ojinaga',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (260,'15','Saucillo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (266,'02','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (267,'04','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (268,'05','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (269,'07','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (270,'08','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (271,'09','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (272,'10','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (273,'12','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (274,'01','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (275,'13','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (276,'14','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (277,'16','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (278,'03','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (279,'06','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (280,'11','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (281,'15','Ciudad de México',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (282,'05','Canatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (286,'01','Victoria de Durango',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (288,'02','Gómez Palacio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (293,'03','Ciudad Lerdo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (297,'09','Nombre de Dios',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (299,'12','Santa María del Oro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (301,'08','Francisco I. Madero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (302,'07','Peñón Blanco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (304,'11','El Salto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (309,'06','San Juan del Río del Centauro del Norte',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (313,'04','Santiago Papasquiaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (319,'10','Vicente Guerrero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (321,'24','Abasolo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (322,'01','Acámbaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (323,'02','San miguel de Allende',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (324,'33','Apaseo el Alto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (325,'28','Apaseo el Grande',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (327,'03','Celaya',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (327,'25','Rincón de Tamayo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (328,'34','Ciudad Manuel Doblado',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (329,'17','Comonfort',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (329,'21','Empalme Escobedo (Escobedo)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (331,'04','Cortazar',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (332,'20','Cuerámaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (333,'38','Doctor Mora',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (335,'31','Marfil',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (335,'05','Guanajuato',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (336,'16','Huanímaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (337,'06','Irapuato',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (338,'35','Jaral del Progreso',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (339,'12','Jerécuaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (340,'07','León de los Aldama',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (341,'08','Moroleón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (343,'19','Pénjamo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (345,'29','Purísima de Bustos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (346,'14','Romita',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (347,'09','Salamanca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (348,'30','Salvatierra',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (349,'36','San Diego de la Unión',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (351,'10','San Francisco del Rincón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (352,'32','San José Iturbide',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (353,'22','San Luis de la Paz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (355,'37','Santa Cruz Juventino Rosas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (356,'13','Santiago Maravatío',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (357,'11','Silao',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (358,'15','Tarandacuao',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (361,'18','Uriangato',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (362,'23','Valle de Santiago',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (364,'26','Villagrán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (366,'27','Yuriria',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (367,'01','Acapulco de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (372,'10','Ciudad Apaxtla de Castrejón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (373,'05','Arcelia',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (377,'07','Atoyac de Álvarez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (378,'06','Ayutla de los Libres',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (379,'30','Azoyú',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (380,'09','San Jerónimo de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (381,'12','Buenavista de Cuellar',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (384,'40','Copala',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (387,'16','Coyuca de Benítez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (388,'14','Coyuca de Catalán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (389,'36','Cuajinicuilapa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (393,'13','Cutzamala de Pinzón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (394,'33','Chilapa de Álvarez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (395,'02','Chilpancingo de los Bravo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (395,'39','Ocotito',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (396,'38','Cruz Grande',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (399,'37','Huamuxtitlan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (400,'26','Huitzuco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (401,'03','Iguala de la Independencia',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (404,'41','Zihuatanejo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (405,'15','Tierra Colorada',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (411,'17','Olinalá',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (414,'21','Petatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (416,'11','Ciudad Altamirano',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (418,'32','San Luis Acatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (419,'29','San Marcos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (421,'04','Taxco de Alarcón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (423,'25','Técpan de Galeana',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (423,'23','San Luis San Pedro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (423,'20','San Luis de la Loma',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (424,'24','Teloloapan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (425,'28','Tepecoacuilco de Trujano',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (427,'27','Tixtla de Guerrero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (431,'35','Tlalixtaquilla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (432,'34','Tlapa de Comonfort',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (433,'31','Tlapehuala',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (434,'22','La Unión',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (441,'19','Zumpango del Río',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (443,'18','Marquelia',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (450,'01','Actopan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (455,'02','Apan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (475,'08','Huejutla de Reyes',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (477,'12','Ixmiquilpan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (495,'03','Pachuca de Soto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (503,'11','Santiago Tulantepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (508,'15','Tepeapulco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (508,'04','Ciudad de Fray Bernardino de Sahagún',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (510,'13','Tepeji del Rio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (516,'10','Tizayuca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (521,'09','Tlaxcoapan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (523,'14','Cruz Azul',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (523,'05','Tula de Allende',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (524,'06','Tulancingo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (531,'07','Zimapan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (533,'55','Acatlán de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (534,'24','Ahualulco de Mercado',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (537,'01','Ameca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (539,'20','Arandas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (544,'17','Atotonilco el Alto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (546,'25','Autlán de Navarro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (549,'32','La Barca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (552,'16','La Resolana',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (553,'36','Cihuatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (554,'02','Ciudad Guzmán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (555,'28','Cocula',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (556,'35','Colotlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (561,'47','Ajijic',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (561,'46','Chapala',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (567,'22','Etzatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (568,'29','El Grullo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (570,'03','Guadalajara',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (573,'50','Huejuquilla el Alto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (577,'18','Jalostotitlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (578,'33','Jamay',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (581,'44','Jocotepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (584,'04','Lagos de Moreno',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (586,'26','Magdalena',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (594,'05','Ocotlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (597,'19','Poncitlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (598,'06','Puerto Vallarta',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (601,'53','Las Pintitas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (601,'43','San José el Verde (El Verde)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (601,'42','El Quince (San José el Quince)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (603,'15','San Diego de Alejandría',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (604,'07','San Juan de los Lagos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (605,'27','San Julián',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (609,'30','San Miguel el Alto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (613,'23','Sayula',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (614,'31','Tala',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (615,'21','Talpa de Allende',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (616,'54','Tamazula de Gordiano',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (618,'45','Tecalitlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (622,'39','Teocaltiche',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (624,'08','Tepatitlán de Morelos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (625,'41','Tequila',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (628,'11','Tlajomulco de Zúñiga',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (629,'09','Tlaquepaque',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (632,'12','Tonalá',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (636,'14','Tototlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (639,'13','Tuxpan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (640,'52','Unión de San Antonio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (642,'56','Valle de Guadalupe',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (645,'38','Villa Corona',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (647,'51','Villa Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (649,'34','Yahualica de González Gallo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (650,'49','Zacoalco de Torres',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (651,'10','Zapopan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (652,'37','Zapotiltic',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (656,'48','San Ignacio Cerro Gordo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (661,'39','Almoloya de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (664,'24','Amatepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (669,'01','Ciudad Adolfo López Mateos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (675,'28','Capulhuac',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (676,'03','Coacalco de Berriozabal',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (680,'17','Cuautitlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (681,'23','Chalco de Díaz Covarrubias',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (685,'27','San Vicente Chicoloapan de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (686,'36','Chiconcuac',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (687,'02','Chimalhuacán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (689,'05','Ecatepec de Morelos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (693,'06','Huixquilucan de Degollado',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (695,'18','Ixtapaluca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (706,'29','Juchitepec de Mariano Riva Palacio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (709,'26','Melchor Ocampo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (710,'08','Metepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (713,'09','Naucalpan de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (714,'10','Ciudad Nezahualcoyotl',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (716,'11','Villa Nicolás Romero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (718,'40','Ocoyoacac',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (726,'07','Los Reyes Acaquilpan (La Paz)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (732,'32','San Mateo Atenco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (737,'12','Tecamac de Felipe Villanueva',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (738,'22','Tejupilco de Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (751,'13','Tepotzotlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (752,'30','Tequixquiac',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (755,'19','Texcoco de Mora',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (760,'14','Tlalnepantla de Baz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (762,'20','Toluca de Lerdo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (764,'15','Santa Maria Tultepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (765,'16','Tultitlán de Mariano Escobedo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (771,'31','Xonacatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (776,'41','Zumpango',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (777,'04','Cuautitlán Izcalli',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (778,'21','Valle de Chalco Solidaridad',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (787,'01','Apatzingán de la Constitución',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (800,'25','Cotija de la Paz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (801,'27','Cuitzeo del Porvenir',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (815,'03','Ciudad Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (819,'19','Huetamo de Núñez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (824,'04','Jacona de Plancarte',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (826,'23','Jiquilpan de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (831,'15','Maravatío de Ocampo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (833,'21','Ciudad Lázaro Cárdenas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (833,'22','Las Guacamayas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (834,'06','Morelia',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (836,'26','Nueva Italia de Ruiz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (846,'13','Paracho de Verduzco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (847,'07','Pátzcuaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (850,'05','La piedad de Cabadas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (852,'17','Puruándiro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (856,'02','Los Reyes de Salgado',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (857,'08','Sahuayo de Morelos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (863,'20','Tacámbaro de Codallos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (866,'14','Tangancícuaro de Arista',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (879,'24','Tuxpan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (883,'09','Uruapan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (887,'18','Yurécuaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (888,'10','Zacapu',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (889,'11','Zamora de Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (891,'16','Zinapécuaro de Figueroa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (893,'12','Heroica Zitácuaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (900,'01','Cuautla (Cuautla de Morelos)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (901,'02','Cuernavaca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (906,'04','Jojutla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (911,'05','Puente de Ixtla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (918,'06','Santa Rosa Treinta',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (919,'08','Tlaquiltenango',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (925,'07','Zacatepec de Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (925,'03','Galeana',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (928,'04','Acaponeta',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (929,'18','Ahuacatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (931,'06','Compostela',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (931,'13','Las Varas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (931,'16','La peñita de Jaltemba',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (933,'11','Ixtlán del Río',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (934,'17','Jala',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (935,'14','Xalisco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (938,'09','Ruiz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (939,'10','San Blas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (940,'15','San pedro Lagunillas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (942,'01','Santiago Ixcuintla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (942,'08','Villa Hidalgo (El Nuevo)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (943,'05','Tecuala',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (944,'02','Tepic',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (944,'07','Francisco I. Madero (Puga)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (945,'03','Tuxpan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (947,'12','Bucerías',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (952,'20','Anáhuac',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (953,'01','Ciudad Apodaca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (956,'15','Cadereyta Jiménez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (959,'12','Ciénega de Flores',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (961,'11','Doctor Arroyo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (965,'21','García',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (966,'02','San Pedro Garza García',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (968,'03','Ciudad General Escobedo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (973,'04','Guadalupe',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (976,'13','Hualahuises',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (978,'22','Ciudad Benito Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (980,'05','Linares',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (985,'06','Montemorelos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (986,'07','Monterrey',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (991,'08','Ciudad Sabinas Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (993,'09','San Nicolás de los Garza',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (995,'10','Ciudad Santa Catarina',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (996,'17','Santiago',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (996,'18','El cercado',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1000,'33','Vicente Camalote',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1004,'52','Asunción Nochixtlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1008,'48','Lagunas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1012,'49','Ciudad Ixtepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1019,'15','Cosolapa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1021,'56','Cuilápam de Guerrero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1023,'30','Chahuites',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1026,'31','Heroica Ciudad de Ejutla de Crespo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1037,'06','Heroica Ciudad de Huajuapan de León',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1041,'01','Juchitán (Juchitán de Zaragoza)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1042,'07','Loma Bonita',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1053,'42','Mariscala de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1055,'05','Matías Romero Avendaño',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1057,'25','Miahuatlán de Porfirio Díaz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1060,'18','Natividad',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1062,'27','El Camarón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1065,'02','Oaxaca de Juárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1066,'23','Ocotlán de Morelos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1071,'14','Putla Villa de Guerrero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1077,'03','Salina Cruz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1105,'59','San Antonio de la Cal',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1122,'54','San Blas Atempa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1132,'12','San Felipe Jalapa de Díaz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1141,'53','San Francisco Ixhuatán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1148,'41','San Francisco Telixtlahuaca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1175,'21','San Juan Bautista Cuicatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1178,'35','San Juan Bautista lo de Soto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1182,'04','San Juan Bautista Tuxtepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1183,'36','San Juan Cacahuatepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1267,'38','San Miguel el Grande',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1275,'22','Villa Sola de Vega',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1292,'40','San Pablo Huitzo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1296,'17','San Pablo Villa de Mitla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1316,'08','Puerto Escondido',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1316,'28','San Pedro Mixtepec -Dto. 22-',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1322,'45','San Pedro Pochutla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1325,'32','San Pedro Tapanatepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1331,'37','San Pedro Totolapa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1332,'09','Río Grande o Piedra Parada',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1346,'51','San Sebastián Tecomaxtlahuaca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1348,'57','El Rosario',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1375,'29','Santa Cruz Itundujia',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1388,'58','Santa Lucia del Camino',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1395,'46','Heroica Ciudad de Tlaxiaco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1411,'20','Santa María Huatulco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1411,'13','Bahias de Huatulco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1465,'44','Santiago Jamiltepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1467,'50','Santiago Juxtlahuaca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1480,'43','Santiago Pinotepa Nacional',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1481,'11','Santiago Suchilquitongo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1513,'55','Santo Domingo Tehuantepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1538,'34','Villa de Tamazulápam del Progreso',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1543,'19','Teotitlán de Flores Magón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1549,'16','Tlacolula de Matamoros',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1555,'26','Unión Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1557,'47','San Juan Bautista Valle Nacional',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1563,'24','Villa de Zaachila',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1568,'39','Zimatlán de Álvarez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1571,'10','Acatlán de Osorio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1583,'17','Amozoc',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1587,'01','Atlixco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1609,'11','Cuautlancingo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1613,'16','Ciudad Serdán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1639,'09','Huauchinango',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1653,'02','Izúcar de Matamoros',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1682,'03','Puebla (Heroica Puebla)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1687,'07','San Andrés Cholula',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1700,'04','San Martín Texmelucan de Labastida',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1708,'08','San Pedro Cholula',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1722,'13','Tecamachalco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1724,'05','Tehuacan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1732,'12','Tepeaca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1742,'06','Teziutlan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1765,'15','Xicotepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1776,'14','Zacatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1791,'04','El Pueblito',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1799,'01','Querétaro',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1801,'02','San Juan del Rio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1804,'02','Cozumel',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1805,'03','Felipe Carrillo Puerto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1806,'07','Isla Mujeres',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1807,'04','Chetumal',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1808,'01','Cancún',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1810,'06','Kantunilkín',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1811,'05','Playa del Carmen',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1813,'08','Bacalar',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1818,'09','Cárdenas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1820,'14','Cedral',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1821,'10','Cerritos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1823,'13','Ciudad del Maíz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1824,'17','Fracción el Refugio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1826,'01','Ciudad Valles',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1828,'07','Charcas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1829,'02','Ébano',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1833,'03','Matehuala',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1837,'04','Rioverde',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1838,'08','Salinas de Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1841,'05','San Luis Potosí',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1845,'19','Santa María del Río',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1848,'06','Soledad de Graciano Sánchez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1849,'12','Tamasopo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1850,'18','Tamazunchale',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1853,'11','Tamuin',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1856,'15','Tierra Nueva',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1863,'16','Villa de Reyes',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1871,'20','El Naranjo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1872,'09','Ahome',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1872,'10','Higuera de Zaragoza',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1872,'23','Topolobampo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1872,'01','Los Mochis',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1873,'15','Angostura',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1876,'21','Cosalá',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1877,'20','Aguaruto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1877,'08','Quila',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1877,'02','Culiacán Rosales',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1878,'11','Choix',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1879,'17','La Cruz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1880,'03','Escuinapa de Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1881,'16','San Blas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1882,'04','Guasave',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1883,'05','Mazatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1883,'12','Villa Unión',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1884,'14','Mocorito',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1885,'18','El rosario',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1886,'06','Guamúchil',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1887,'22','San Ignacio',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1888,'19','Estación Naranjo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1888,'13','Sinaloa de Leyva',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1889,'07','Navolato',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1889,'24','Lic. Benito Juárez (Campo Gobierno)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1891,'02','Agua Prieta',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1906,'03','Heroica Caborca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1907,'04','Ciudad Obregón',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1908,'12','Heroica Ciudad de Cananea',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1914,'05','Empalme',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1918,'06','Heroica Guaymas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1919,'07','Hermosillo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1922,'08','Huatabampo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1925,'14','Magdalena de Kino',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1931,'09','Navojoa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1932,'10','Heroica Nogales',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1937,'11','Puerto Peñasco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1944,'01','San Luis Río Colorado',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1959,'13','Sonoita',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1963,'01','Cárdenas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1964,'11','Frontera',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1965,'02','Villahermosa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1966,'03','Comalcalco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1967,'12','Cunduacán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1968,'04','Emiliano Zapata',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1969,'13','Huimanguillo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1971,'05','Jalpa de Méndez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1973,'07','Macuspana',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1975,'10','Paraíso',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1977,'09','Teapa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1978,'08','Tenosique de Pino Suárez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1981,'01','Altamira',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1985,'02','Ciudad Camargo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1987,'03','Ciudad Madero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1990,'12','González',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1990,'15','Estación Manuel (Úrsulo Galván)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1992,'20','Nueva Ciudad Guerrero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1993,'14','Ciudad Gustavo Díaz Ordaz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1995,'13','Jaumave',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (1999,'04','Ciudad Mante',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2000,'05','Heroica Matamoros',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2003,'17','Ciudad Miguel Alemán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2005,'06','Nuevo Laredo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2010,'07','Reynosa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2011,'08','Ciudad Río Bravo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2013,'09','San Fernando',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2015,'18','Soto la Marina',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2016,'10','Tampico',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2017,'19','Ciudad Tula',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2018,'21','Valle Hermoso',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2019,'11','Ciudad Victoria',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2021,'16','Xicoténcatl',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2026,'01','Apizaco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2027,'05','Calpulalpan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2031,'06','Chiautempan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2034,'04','Huamantla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2046,'02','Villa Vicente Guerrero',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2054,'03','Tlaxcala (Tlaxcala de Xicotencatl)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2084,'01','Acayucan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2091,'39','Altotonga',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2092,'34','Alvarado',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2094,'02','Naranjos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2095,'37','Paraje Nuevo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2096,'50','Ángel R. Cabada',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2097,'35','José Cardel',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2102,'56','Atoyac',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2102,'48','General Miguel Alemán (Potrero Nuevo)',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2107,'36','Banderilla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2109,'03','Boca del RÍo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2113,'45','Catemaco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2114,'58','Cazones de Herrera',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2115,'61','Cerro Azul',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2119,'04','Coatepec',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2120,'06','Coatzacoalcos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2121,'49','Coatzintla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2125,'07','Córdoba',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2126,'19','Cosamaloapan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2129,'53','Cosoleacaque',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2134,'32','Cuitláhuac',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2142,'47','Las Choapas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2149,'33','Fortín de las Flores',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2150,'25','Gutiérrez Zamora',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2152,'28','Huatusco de Chicuellar',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2153,'43','Huayacocotla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2154,'40','Juan Díaz Covarrubias',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2155,'57','Huiloapan de Cuauhtémoc',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2158,'31','Isla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2166,'29','Ixtaczoquitlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2168,'10','Xalapa-Enríquez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2170,'09','Jáltipan de Morelos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2175,'27','Juan Rodríguez Clara',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2178,'54','Lerdo de Tejada',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2189,'11','Minatitlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2192,'41','Cuichapa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2196,'46','Nogales',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2199,'12','Orizaba',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2204,'21','Pánuco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2205,'13','Papantla de Olarte',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2206,'68','Paso del Macho',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2207,'44','Paso de Ovejas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2210,'26','Platón Sánchez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2211,'38','Playa Vicente',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2212,'14','Poza Rica de Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2219,'30','Río Blanco',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2222,'15','San Andrés Tuxtla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2222,'66','Sihuapan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2224,'42','Santiago Tuxtla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2229,'60','Soledad de Doblado',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2233,'22','Tampico Alto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2236,'24','Tantoyuca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2242,'23','Tempoal de Sánchez',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2254,'62','Tezonapa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2255,'18','Tierra Blanca',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2256,'55','Tihuatlán',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2257,'52','Tlacojalpan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2264,'69','Tlapacoyan',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2270,'16','Túxpam de Rodríguez Cano',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2274,'17','Veracruz',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2278,'59','Yecuatla',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2285,'05','Agua dulce',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2286,'67','El Higo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2288,'08','Tres Valles',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2289,'20','Carlos A. Carrillo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2292,'51','San Rafael',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2334,'06','Kanasín',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2343,'01','Mérida',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2345,'04','Motul de Carrillo Puerto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2382,'03','Ticul',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2389,'02','Tizimín',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2395,'05','Valladolid',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2404,'12','Víctor Rosales',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2407,'06','Ciudad Cuauhtémoc',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2409,'01','Fresnillo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2416,'04','Guadalupe',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2418,'17','Jalpa',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2419,'02','Jerez de García Salinas',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2421,'19','Juan Aldama',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2423,'18','Loreto',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2424,'14','Luis Moya',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2432,'15','Moyahua de Estrada',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2433,'11','Nochistlán de Mejía',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2435,'07','Ojocaliente',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2438,'05','Río Grande',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2441,'16','Sombrerete',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2448,'13','Valparaíso',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2450,'10','Villa de Cos',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2453,'08','Villa Hidalgo',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2454,'09','Villanueva',1);
INSERT INTO `t204_c_ciudad` (`id_202_municipio`,`cve_ciudad`,`nm_ciudad`,`st_vigente`) VALUES (2455,'03','Zacatecas',1);
